# Numerical Computing with NumPy

NumPy is the foundation of scientific computing in Python. Its core innovation is the *ndarray*: a typed, multi-dimensional array that supports vectorised operations. Instead of looping over elements one by one, you write operations that apply to the whole array at once, and NumPy executes them in optimised C code. The speed difference over plain Python loops can be 10–100×.

**What's inside:** creating arrays, indexing and slicing, element-wise arithmetic, broadcasting, universal functions (ufuncs), aggregation along axes, reshaping, and linear algebra.

**Learn more:** [NumPy documentation](https://numpy.org/)

## Setup

In [ ]:
%pip install numpy

## 1. Creating Arrays

### 1.1 From a list

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [2]:
# 2D array from nested lists
m = np.array([[1, 2, 3], [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

### 1.2 zeros / ones / full

In [3]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [5]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

### 1.3 arange

Like Python's `range()` but returns an array.

In [6]:
np.arange(0, 10, 2)   # start, stop (exclusive), step

array([0, 2, 4, 6, 8])

### 1.4 linspace

Evenly spaced values between two endpoints, useful for plotting.

In [7]:
np.linspace(0, 1, 5)   # 5 values from 0 to 1 inclusive

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 1.5 Random arrays

In [8]:
rng = np.random.default_rng(seed=42)   # reproducible results
rng.integers(0, 100, size=5)

array([ 8, 77, 65, 43, 43])

In [9]:
rng.standard_normal(size=(2, 3)).round(2)

array([[ 0.94, -1.95, -1.3 ],
       [ 0.13, -0.32, -0.02]])

## 2. Array Attributes

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

print(a.shape)   # (rows, columns)
print(a.ndim)    # number of dimensions
print(a.dtype)   # element type
print(a.size)    # total element count

(2, 3)
2
float64
6


## 3. Indexing and Slicing

### 3.1 1D indexing and slicing

In [11]:
a = np.arange(10)
print(a[3])     # single element
print(a[-1])    # last element
print(a[2:7])   # slice
print(a[::2])   # every other element

3
9
[2 3 4 5 6]
[0 2 4 6 8]


### 3.2 2D indexing

`m[row, col]`: comma-separated indices instead of chained brackets.

In [12]:
m = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(m[1, 2])      # row 1, col 2
print(m[:, 1])      # entire column 1
print(m[0:2, 1:])   # sub-matrix

60
[20 50 80]
[[20 30]
 [50 60]]


### 3.3 Boolean indexing

Pass a boolean array as the index; returns only elements where True.

In [13]:
a = np.array([3, 7, 1, 9, 4])
a[a > 4]

array([7, 9])

In [14]:
a[a % 2 == 0]   # even elements only

array([4])

## 4. Arithmetic and Broadcasting

Operations are element-wise by default (no loops needed).

### 4.1 Element-wise arithmetic

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(a * b)
print(b / a)

[11 22 33]
[10 40 90]
[10. 10. 10.]


### 4.2 Scalar broadcasting

A scalar is automatically applied to every element.

In [16]:
a = np.array([1, 2, 3])
a * 10

array([10, 20, 30])

### 4.3 Array broadcasting

Arrays with compatible shapes can be combined without explicit tiling.

In [17]:
# 1D row array broadcast across each row of a 3x3 matrix
m = np.ones((3, 3), dtype=int)
row = np.array([1, 2, 3])
m + row

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [18]:
# column array (shape 3x1) broadcast across each column
col = np.array([[10], [20], [30]])
m + col

array([[11, 11, 11],
       [21, 21, 21],
       [31, 31, 31]])

## 5. Universal Functions (ufuncs)

NumPy provides vectorised math functions that operate on entire arrays at once.

In [19]:
a = np.array([0, 1, 4, 9, 16])
np.sqrt(a)

array([0., 1., 2., 3., 4.])

In [20]:
np.exp(np.array([0, 1, 2])).round(4)

array([1.    , 2.7183, 7.3891])

In [21]:
a = np.array([-3, -1, 0, 1, 3])
np.abs(a)

array([3, 1, 0, 1, 3])

In [22]:
a = np.array([1.2, 2.7, 3.5])
print(np.floor(a))
print(np.ceil(a))
print(np.round(a))

[1. 2. 3.]
[2. 3. 4.]
[1. 3. 4.]


## 6. Aggregation Along Axes

`axis=0` collapses rows (result is one value per column); `axis=1` collapses columns.

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.sum())
print(a.mean())
print(a.std().round(4))
print(a.min(), a.max())

21
3.5
1.7078
1 6


In [24]:
# axis=0: collapse rows (result is one value per column)
a.sum(axis=0)

array([5, 7, 9])

In [25]:
# axis=1: collapse columns (result is one value per row)
a.sum(axis=1)

array([ 6, 15])

In [26]:
a.mean(axis=1)

array([2., 5.])

## 7. Reshaping

### 7.1 reshape

Change the shape without changing the data. Use -1 to let NumPy infer a dimension.

In [27]:
a = np.arange(12)
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a.reshape(4, -1)   # -1 means 'infer this dimension'

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 7.2 flatten and ravel

In [29]:
m = np.array([[1, 2], [3, 4]])

print(m.flatten())   # always returns a copy
print(m.ravel())     # returns a view when possible (more efficient)

[1 2 3 4]
[1 2 3 4]


### 7.3 Transpose

In [30]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 8. Linear Algebra

### 8.1 Dot product (1D vectors)

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)   # 1*4 + 2*5 + 3*6 = 32

np.int64(32)

### 8.2 Matrix multiplication

The `@` operator performs matrix multiplication.

In [32]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B

array([[19, 22],
       [43, 50]])

### 8.3 Determinant and inverse

In [33]:
A = np.array([[1, 2], [3, 4]], dtype=float)

print(np.linalg.det(A))
print(np.linalg.inv(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
